apiVersion: v1
kind: Service
metadata:
  name: iris-classifier-service
spec:
  selector:
    app: iris-classifier-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8600
  type: LoadBalancer
