name: Continuous Integration

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Python Setup
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install Requirements
        run: |
          pip install dvc dvc_gs pandas joblib pytest scikit-learn
      - name: Setup GCP Service Account Key
        run: |
          echo "${{ secrets.GCP_KEY_JSON }}" > key.json
          export GOOGLE_APPLICATION_CREDENTIALS="key.json"
      - name: Configure DVC Remote
        run: dvc remote modify --local bucketremote credentialpath key.json
      - name: DVC Pull and Checkout For Generating the data files
        run: |
          python -m json.tool key.json
          dvc pull
          dvc checkout
      - name: PyTest File Execution
        run: |
          pytest test_evaluation.py > results.txt
          cat results.txt 
